#!/usr/bin/env bash
# Install and configure HAproxy on your lb-01 server.
sudo apt-get -y update
sudo apt-get install -y haproxy

echo "
defaults
    timeout connect 10s
    timeout client 30s
    timeout server 30s
    log global
    mode http

frontend haproxynode
    bind *:80
    mode http
    default_backend backendnodes

backend backendnodes
    balance roundrobin
    option forwardfor
    server 425235-lb-01 107.23.108.224 check
    server 425235-web-02 54.209.218.95 check

listen stats
    bind :32700
    stats enable
    stats uri /" >> /etc/haproxy/haproxy.cfg

sudo haproxy -f /etc/haproxy/haproxy.cfg -c
sudo service haproxy restart
